export const theme = {
  colors: {
    primary: '#181b31',
    primaryContainer: '#2d3047',
    secondary: '#6c5b50',
    secondaryContainer: '#f5ded0',
    tertiary: '#715858',
    tertiaryContainer: '#f2d1d1',
    background: '#FCFCFA',
    surface: '#FFFFFF',
    surfaceVariant: '#e5e1e4',
    text: '#1A1523',
    textSecondary: '#5B586E',
    border: '#DFE6E9',
    borderSubtle: 'rgba(26, 21, 35, 0.1)',
    success: '#00B894',
    warning: '#FDCB6E',
    error: '#ba1a1a',
    errorContainer: '#ffdad6',
    onErrorContainer: '#93000a',
  },
  spacing: {
    xs: 8,
    sm: 16,
    md: 24,
    lg: 32,
    xl: 48,
    xxl: 64,
  },
  typography: {
    families: {
      display: 'Newsreader',
      body: 'Plus Jakarta Sans',
    },
    sizes: {
      xs: 12,
      sm: 14,
      md: 16,
      lg: 18,
      xl: 24,
      xxl: 36,
      xxxl: 48,
    },
    weights: {
      regular: '400' as const,
      medium: '500' as const,
      semiBold: '600' as const,
      bold: '700' as const,
    },
  },
  borderRadius: {
    sm: 4,
    md: 8,
    lg: 16,
    xl: 24,
    round: 9999,
  },
};
